### ISSUE TITLE
Unable to view logs

### ISSUE THREAD

**Issue by Evanslooten** [Laravel-Backpack/LogManager#24]
# Bug report

### What I did:
Installed LogManager via composer command in read me, setup the file system driver, added the URL to the sidebar, clicked the link when logged in.
### What I expected to happen:
Show a list of log files
### What happened:
Whoops! Illegal string offset 'file_name'.
### What I've already tried to fix it:
I dumped out $file in the loop, it is not an array but a string file path. I was able to get the screen to load replacing the $file['xxx'] with variables using filesystem functions. This does let the screen load, but when attempting to preview the log it fails. 

Possibly a this-instance Laravel configuration issue?
### Backpack, Laravel, PHP, DB version:
3.4, 5.6, 7.1.11, 5.7.2 MySQL

**Comment by tabacitu** [comment]
Hmm... that's very weird @Evanslooten . I've just installed it on a fresh instance, with exactly your versions, and it works just fine for me: https://cl.ly/0e1I3326093D

And actually, $file is an array for me - it's the array that Filesystem returns for a file:
![screen shot 2018-05-02 at 07 53 43](https://user-images.githubusercontent.com/1032474/39505899-09cc40a6-4dde-11e8-8862-f5f8e3abde7e.png)

I have no idea what the problem was for you, or what to recommend to solve it. Heck, maybe a ```composer update```? Very sorry for this.

Cheers!

PS. If anybody else has this problem, please speak up and reopen this issue. Would love to get to the bottom of this.
