### ISSUE TITLE
Payload invalid, DecryptException thrown

### ISSUE THREAD

**Issue by sheriffmarley** [Laravel-Backpack/LogManager#28]
# Bug report

### What I did:
I tried to access a log file (laravel-2019-05-19.log)

### What I expected to happen:
Show the logfile

### What happened:
A DecryptException was thrown
`The payload is invalid. {"userId":1,"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /var/www/html/main/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:195)`

### What I've already tried to fix it:
Since the filename seems to be only a base64 encoded string, I replaced `decrypt($file_name)` with `base64_decode($file_name)` and it worked.

### Backpack, Laravel, PHP, DB version:
Backpack: 3.6.21
LogManager: 2.3.26
Laravel: 5.8.17
PHP: 7.3.3

**Comment by tabacitu** [comment]
Hi @sheriffmarley ,

Yes, we've indeed [changed the filename encryption](https://github.com/Laravel-Backpack/LogManager/commit/36e52a44977191414e766c4067caf75d36c6351e) from base64 to Laravel's default - we believe that's better security. With ```encrypt()```/```decrypt()``` people can't base64encode a filename they want, and pass it to the URL. Not even admins, which we usually trust.

You can see in my link above that the changes have been both in the LogController, and in the blade files. I suspect you've run ```composer update```, so have the latest controller, but have the old blade file, by having published it to your ```resources/views/vendor/backpack/logmanager/logs.blade.php```. If your blade file uses base64 instead of encrypt/decrypt, take a look at the changes we've made in the link above (they're super simple) and do them to your blade file too.

Cheers!

**Comment by 666lampshadesOG** [comment]
# Bug report

### What I did:

Tried following this answer but no luck: https://github.com/Laravel-Backpack/LogManager/issues/28#issuecomment-494299732  ( i have the correct blade files )

I get errors when I view the logs.

I deleted the logmanager folder and reinstalled with composer with the following settings

```
        "backpack/base": "^1.0",
        "backpack/crud": "^3.5",
        "backpack/logmanager": "^2.3",
```

### What I expected to happen:

I expected I could view my logs.

### What happened:

When I view log, I get error

domain.co/admin/log/preview/bGFyYXRlbC0yMEE5LTA4LTMxLmxvZw==

```
 Illuminate \ Contracts \ Encryption \ DecryptException
The payload is invalid.
```
```
vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php
```

```
        if (! $this->validPayload($payload)) {
            throw new DecryptException('The payload is invalid.');
        }
```

### What I've already tried to fix it:

Tried deleting the logmanager folder and reinstalling with composer.

Tried deleting all log files

### Backpack, Laravel, PHP, DB version:

```
"backpack/base": "^1.0",
"backpack/crud": "^3.5",
"backpack/logmanager": "^2.3",
"laravel/framework": "5.7.*",
"php": "^7.1.3",
```

**Comment by Bajranggithub** [comment]
Illuminate \ Contracts \ Encryption \ DecryptException
The payload is invalid.
