### ISSUE TITLE
LogManager is missing the first breadcrumb

### ISSUE THREAD

**Issue by timdiels1** [Laravel-Backpack/LogManager#3]
The LogManager is missing its first breadcrumb:

<img width="1043" alt="screen shot 2016-09-17 at 21 27 47" src="https://cloud.githubusercontent.com/assets/7079398/18610475/a0569e4c-7d1d-11e6-87e4-5f9e97db9f0a.png">

I have created a patch to solve the issues. Will need help to create a pull request.

**Comment by timdiels1** [comment]
Can't seem to create a pull request. So here is the solution:

So in `src/resources/views/` in both files we have to go from

```
 <li><a href="{{ url('admin') }}">{{ config('base.project_name') }}</a></li>
```

to

```
 <li><a href="{{ url('admin') }}">{{ config('backpack.base.project_name') }}</a></li>
```

**Comment by twmbx** [comment]
@timdiels1 I've noticed this too... I agree with the fix.

There is a larger issue though however; most of the rest of Backpack is build on top of CRUD and that uses "Admin" as the root breadcrumb pointing to the /admin endpoint.
A convention would need to be settled on as far as how the breadcrumbs look so that the UI is uniform across the packages.

Thoughts @tabacitu ?

**Comment by tabacitu** [comment]
Hi guys,

@timdiels1 , @twoSeats, I think you're both right, thank you! It's broken, and it should be "_Admin_" to keep consistency. Just updated it, a `composer update` should fix this for you. 

@timdiels1 , regarding how to use pull requests:
- happy to help, we should [chat on Gitter](https://gitter.im/BackpackForLaravel/Lobby) when you want to make your next contribution;
- I'm currently working on an article on [Medium](https://medium.com/@tabacitu) to explain what I think the easiest workflow is for PHP projects that use git, composer and Github. I hope I'll have time to finish it soon;

Thanks for pitching in, guys!

Cheers!
