### ISSUE TITLE
README instructions don't match docs in backpackforlaravel.com

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/LogManager#48]
I was reading [LogManager](https://backpackforlaravel.com/docs/4.1/install-optionals#logmanager) and there are differences between the README of this repo and website documentation.

Which one is correct?

**Comment by pxpm** [comment]
@shinokada thanks for raising the issue, my guess is that the docs on the Website are more accurate and up to date. 

Did you happen to follow any of them ? Any error you spotted ? 

Thanks,
Pedro

**Comment by shinokada** [comment]
@pxpm 
Thank you for your reply.
I created [backpack_install](https://github.com/shinokada/backpack_install) following the website doc. It seems there are differences and for newbies, it may create confusion.

So it may be a good idea to update the repo README aligned to the website doc.

**Comment by pxpm** [comment]
Sure, I will add this to a project so we can have a look at it!

Thanks for the report and for the tool. 

May I just ask why shell? Like to explore or something ? In a "Laravel" world you would expect an "Backpack Installer" package instead of shell scripts. I think it's OP ! :)

As far as I go is: 

```shell
taskkill /F /FI "SERVICES eq wampapache64"
start /d "c:\wamp64\bin\apache\apache2.4.46\bin\" httpd.exe
```

To stop my apache service and start it as an SO app. 👍 😄 

Thanks again,
Pedro

**Comment by shinokada** [comment]
I don't use Windows, so I didn't know about the Backpack Installer.

I like Bash scripting because it automates all my repetitive work.

Thanks for updates.
